project:
  type: website

website:
  title: "tutorial-fmriprep"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  freeze: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
